language: ruby
rvm:
  - 2.3
services:
  - mysql
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mass_bail_fund_test;'
